# Dependencies

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Grab Bag Game Studio
tagline:          'Dev Blog'
description:      ''
url:              http://blog.grabbaggamestudio.com
baseurl:          /

author:
  name:           'Grab Bag Game Studio'
  url:            http://grabbaggamestudio.com

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           
